services:
  dev-clt-mask-bloc-bot:
    container_name: dev-clt-mask-bloc-bot
    image: ghcr.io/Charlotte-Mask-Bloc/clt-mask-bloc-bot:dev
    env_file: .env.dev
    deploy:
      mode: global
    restart: always

  prod-clt-mask-bloc-bot:
    container_name: prod-clt-mask-bloc-bot
    image: ghcr.io/Charlotte-Mask-Bloc/clt-mask-bloc-bot:prod
    env_file: .env.prod
    deploy:
      mode: global
    restart: always

  clt-watchtower:
    container_name: clt-mask-bloc-bot-watchtower
    image: containrrr/watchtower
    command:
      - "dev-clt-mask-bloc-bot"
      - "prod-clt-mask-bloc-bot"
      - "--interval"
      - "30"
      - "--cleanup"
      - "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
    restart: always

