services:
  dev-clt-mask-bloc-bot:
    container_name: dev-clt-mask-bloc-bot
    image: ghcr.io/charlotte-mask-bloc/clt-mask-bloc-bot:dev
    env_file: .env.dev
    deploy:
      mode: global
    restart: always
    labels: [ "com.centurylinklabs.watchtower.scope=clt-mask-bloc-bot" ]

  prod-clt-mask-bloc-bot:
    container_name: prod-clt-mask-bloc-bot
    image: ghcr.io/charlotte-mask-bloc/clt-mask-bloc-bot:prod
    env_file: .env.prod
    deploy:
      mode: global
    restart: always
    labels: [ "com.centurylinklabs.watchtower.scope=clt-mask-bloc-bot" ]

  clt-watchtower:
    container_name: clt-mask-bloc-bot-watchtower
    image: containrrr/watchtower
    command:
      - "dev-clt-mask-bloc-bot"
      - "prod-clt-mask-bloc-bot"
      - "--interval"
      - "30"
      - "--cleanup"
      - "true"
      - "--scope"
      - "clt-mask-bloc-bot"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
    restart: always
    labels: [ "com.centurylinklabs.watchtower.scope=clt-mask-bloc-bot" ]

